In [8]:
from tensorflow.keras.preprocessing.text import one_hot
import numpy as np
import pandas as pd

In [4]:
input = ['my name is sachin',
         'i am 26 years old',
         'i live in the uk',
         'physco thats the wrong number']
input

['my name is sachin',
 'i am 26 years old',
 'i live in the uk',
 'physco thats the wrong number']

In [5]:
# def vocb size
voc_size = 10000

one_hot_rep = [one_hot(words, voc_size)for words in input]
one_hot_rep


[[7840, 5973, 6322, 3888],
 [7302, 3614, 2362, 7691, 1665],
 [7302, 5167, 5524, 7280, 9163],
 [7590, 3178, 7280, 6547, 626]]

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
input_lenth = 5
embed_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=input_lenth)
embed_docs

array([[   0, 7840, 5973, 6322, 3888],
       [7302, 3614, 2362, 7691, 1665],
       [7302, 5167, 5524, 7280, 9163],
       [7590, 3178, 7280, 6547,  626]])

In [12]:
# feature representation
dim = 8

model = Sequential()
model.add(Embedding(voc_size, dim, input_length = input_lenth))
model.compile('adam', 'mse')

In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 8)              80000     
                                                                 
Total params: 80000 (312.50 KB)
Trainable params: 80000 (312.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embed_docs)

1/1 [==============================] - 1s 1s/step


array([[[ 2.4888802e-02, -3.7235774e-02,  4.4332173e-02,  9.7999796e-03,
         -2.7106656e-02,  4.3215267e-03, -1.8752445e-02,  1.8859420e-02],
        [-4.9714148e-02,  2.1331456e-02, -3.7761461e-02, -1.9961894e-02,
         -1.9004829e-03,  4.0973973e-02, -4.6014976e-02,  1.8280927e-02],
        [ 3.8677935e-02, -3.8775325e-02,  2.2507284e-02,  2.1509457e-02,
         -2.9908825e-02,  1.2042426e-02, -3.2989278e-02,  3.4785639e-02],
        [-9.3026273e-03,  3.5511617e-02,  4.3200981e-02, -3.5400309e-02,
          1.9580770e-02, -1.4835320e-02,  3.3460762e-02,  5.1396862e-03],
        [ 2.9377613e-02,  2.8925922e-02,  4.3902252e-02, -1.5206791e-02,
          3.4483936e-02,  1.8183317e-02, -2.0998288e-02, -2.5675714e-02]],

       [[ 3.8825367e-02,  4.4677369e-03,  3.2809231e-02,  3.2334808e-02,
          2.5946926e-02,  4.7038462e-02,  3.1646144e-02,  2.0494685e-03],
        [-4.1261539e-03,  3.7489403e-02,  3.4706164e-02, -8.3554536e-05,
          4.2493943e-02, -1.0806549e-02,  2

In [15]:
embed_docs[0]

array([   0, 7840, 5973, 6322, 3888])

In [17]:
model.predict(embed_docs[0])

1/1 [==============================] - 0s 33ms/step


array([[ 0.0248888 , -0.03723577,  0.04433217,  0.00979998, -0.02710666,
         0.00432153, -0.01875244,  0.01885942],
       [-0.04971415,  0.02133146, -0.03776146, -0.01996189, -0.00190048,
         0.04097397, -0.04601498,  0.01828093],
       [ 0.03867793, -0.03877532,  0.02250728,  0.02150946, -0.02990882,
         0.01204243, -0.03298928,  0.03478564],
       [-0.00930263,  0.03551162,  0.04320098, -0.03540031,  0.01958077,
        -0.01483532,  0.03346076,  0.00513969],
       [ 0.02937761,  0.02892592,  0.04390225, -0.01520679,  0.03448394,
         0.01818332, -0.02099829, -0.02567571]], dtype=float32)